services:
  - type: web
    name: obfuscator
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_BUCKET
        value: your-bucket-name
